name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: pip
      - name: Install Python Dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Run Pytest
        run: pytest
